# Generated by Django 5.0.3 on 2024-11-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiva', '0001_initial'),
    ]

    operations = [
    ]
