# Generated by Django 5.0.3 on 2024-10-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
