# Generated by Django 5.0.3 on 2024-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost_in_generate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost_in_credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
