# Generated by Django 5.0.3 on 2024-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_service_cost_in_generate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
